cp  /data/kibana-5.6.9-linux-x86_64/optimize/bundles/timelion.bundle.js  /opt/kibana-cn/timelion.bundle.js
cp  /data/kibana-5.6.9-linux-x86_64/optimize/bundles/commons.bundle.js  /opt/kibana-cn/commons.bundle.js
cp  /data/kibana-5.6.9-linux-x86_64/optimize/bundles/kibana.bundle.js  /opt/kibana-cn/kibana.bundle.js
cp  /data/kibana-5.6.9-linux-x86_64/src/ui/public/chrome/directives/global_nav/global_nav.js  /opt/kibana-cn/global_nav.js
cp  /data/kibana-5.6.9-linux-x86_64/src/core_plugins/timelion/index.js  /opt/kibana-cn/timelion-index.js
cp  /data/kibana-5.6.9-linux-x86_64/src/core_plugins/kibana/index.js  /opt/kibana-cn/kibana-index.js
cp  /data/kibana-5.6.9-linux-x86_64/src/core_plugins/kibana/public/dashboard/listing/dashboard_listing.html  /opt/kibana-cn/dashboard_listing.html
cp  /data/kibana-5.6.9-linux-x86_64/src/core_plugins/kibana/translations/en.json  /opt/kibana-cn/en.json
cp  /data/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/horizontal_bar.js  /opt/kibana-cn/horizontal_bar.js
cp  /data/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/histogram.js  /opt/kibana-cn/histogram.js
cp  /data/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/area.js  /opt/kibana-cn/area.js
cp  /data/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/line.js  /opt/kibana-cn/line.js
cp  /data/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/heatmap.js  /opt/kibana-cn/heatmap.js
