cp /data/kibana-cn/timelion.bundle.js   /opt/kibana-5.6.9-linux-x86_64/optimize/bundles/timelion.bundle.js
cp /data/kibana-cn/commons.bundle.js   /opt/kibana-5.6.9-linux-x86_64/optimize/bundles/commons.bundle.js
cp /data/kibana-cn/kibana.bundle.js   /opt/kibana-5.6.9-linux-x86_64/optimize/bundles/kibana.bundle.js
cp /data/kibana-cn/global_nav.js   /opt/kibana-5.6.9-linux-x86_64/src/ui/public/chrome/directives/global_nav/global_nav.js
cp /data/kibana-cn/timelion-index.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/timelion/index.js
cp /data/kibana-cn/kibana-index.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kibana/index.js
cp /data/kibana-cn/dashboard_listing.html   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kibana/public/dashboard/listing/dashboard_listing.html
cp /data/kibana-cn/en.json   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kibana/translations/en.json
cp /data/kibana-cn/horizontal_bar.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/horizontal_bar.js
cp /data/kibana-cn/histogram.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/histogram.js
cp /data/kibana-cn/area.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/area.js
cp /data/kibana-cn/line.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/line.js
cp /data/kibana-cn/heatmap.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/heatmap.js
