cp /opt/kibana-cn-master/5.6.9/timelion.bundle.js   /opt/kibana-5.6.9-linux-x86_64/optimize/bundles/timelion.bundle.js
cp /opt/kibana-cn-master/5.6.9/commons.bundle.js   /opt/kibana-5.6.9-linux-x86_64/optimize/bundles/commons.bundle.js
cp /opt/kibana-cn-master/5.6.9/kibana.bundle.js   /opt/kibana-5.6.9-linux-x86_64/optimize/bundles/kibana.bundle.js
cp /opt/kibana-cn-master/5.6.9/global_nav.js   /opt/kibana-5.6.9-linux-x86_64/src/ui/public/chrome/directives/global_nav/global_nav.js
cp /opt/kibana-cn-master/5.6.9/timelion-index.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/timelion/index.js
cp /opt/kibana-cn-master/5.6.9/kibana-index.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kibana/index.js
cp /opt/kibana-cn-master/5.6.9/dashboard_listing.html   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kibana/public/dashboard/listing/dashboard_listing.html
cp /opt/kibana-cn-master/5.6.9/en.json   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kibana/translations/en.json
cp /opt/kibana-cn-master/5.6.9/horizontal_bar.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/horizontal_bar.js
cp /opt/kibana-cn-master/5.6.9/histogram.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/histogram.js
cp /opt/kibana-cn-master/5.6.9/area.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/area.js
cp /opt/kibana-cn-master/5.6.9/line.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/line.js
cp /opt/kibana-cn-master/5.6.9/heatmap.js   /opt/kibana-5.6.9-linux-x86_64/src/core_plugins/kbn_vislib_vis_types/public/heatmap.js
